import Head from 'next/head'
import Gradient from '../components/gradient'
import Header from '../components/header'

const Home = () => {
  return (
    <>
      <Head>
        <title>Joe Grant - Frontend Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Gradient />
      <div className='container'>
        <h2>Test</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo maxime fugiat consequatur officiis suscipit nam ullam sint necessitatibus adipisci inventore explicabo quaerat, minus eius animi mollitia et quos aliquam aliquid.</p>
      </div>

    </>
  )
}

export default Home;